# Generated by Django 4.2 on 2024-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Токен для авторизации', max_length=100, null=True, verbose_name='Токен'),
        ),
    ]
