# Generated by Django 5.0.6 on 2024-07-19 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название заголовка', max_length=200, verbose_name='Название заголовка')),
                ('slug', models.CharField(help_text='Сгенерируется автоматически из названия заголовка', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(help_text='Описание блога', max_length=1000, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='photo/product', verbose_name='Фото')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
